INSERT INTO CATEGORIAS (nombre, abbr, imagen) VALUE
						("BEBES","BEB", "url5");
                        
INSERT INTO PRODUCTOS (nombre, precio, disponible ) VALUES
					  ("SANDALIAS BOB TORONJA", 19.90, true);


SELECT * FROM CATEGORIAS INNER JOIN PRODUCTOS ON CATEGORIAS.ID = PRODUCTOS.CATEGORIA_ID;

SELECT * FROM CATEGORIAS LEFT JOIN PRODUCTOS ON CATEGORIAS.ID = PRODUCTOS.CATEGORIA_ID;

SELECT * FROM CATEGORIAS RIGHT JOIN PRODUCTOS ON CATEGORIAS.ID = PRODUCTOS.CATEGORIA_ID;

