# Generated by Django 3.2.4 on 2021-06-16 01:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoModel',
            fields=[
                ('prestamoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('prestamoFechaInicio', models.DateField(db_column='fecha_inicio', default=datetime.datetime(2021, 6, 15, 20, 59, 32, 821055), verbose_name='Fecha de inicio del prestamo')),
                ('prestamoFechaFin', models.DateField(db_column='fecha_fin', verbose_name='Fecha de fin del prestamo')),
                ('prestamoEstado', models.BooleanField(db_column='estado', default=True, help_text='Indique el estado del prestamo', verbose_name='Estado del prestamo')),
                ('libro', models.ForeignKey(db_column='libro_id', help_text='Seleccione el libro a prestar', on_delete=django.db.models.deletion.PROTECT, related_name='libroPrestamos', to='gestion.libromodel', verbose_name='Libro')),
                ('usuario', models.ForeignKey(db_column='usuario_id', help_text='Seleccione el usuario a prestar', on_delete=django.db.models.deletion.CASCADE, related_name='usuarioPrestamos', to='gestion.usuariomodel', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'prestamo',
                'verbose_name_plural': 'prestamos',
                'db_table': 'prestamos',
                'ordering': ['-prestamoFechaInicio'],
            },
        ),
    ]
