# Generated by Django 3.2.4 on 2021-06-16 02:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_prestamomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamomodel',
            name='prestamoFechaInicio',
            field=models.DateField(db_column='fecha_inicio', default=django.utils.timezone.now, verbose_name='Fecha de inicio del prestamo'),
        ),
    ]
