# Generated by Django 3.2.4 on 2021-06-18 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_prestamomodel_prestamofechainicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='libromodel',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libromodel',
            name='deletedAt',
            field=models.DateTimeField(db_column='deleted_at', null=True),
        ),
        migrations.AddField(
            model_name='libromodel',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, db_column='updated_at'),
        ),
    ]
