# Generated by Django 3.2.4 on 2021-06-24 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuarioId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('usuarioNombre', models.CharField(db_column='nombre', max_length=20)),
                ('usuarioApellido', models.CharField(db_column='apellido', max_length=20)),
                ('usuarioCorreo', models.EmailField(db_column='correo', max_length=254, unique=True)),
                ('usuarioTipo', models.IntegerField(choices=[(1, 'ADMINISTRADOR'), (2, 'CAJERO'), (3, 'MOZO')], db_column='tipo')),
                ('usuarioTelefono', models.CharField(db_column='telefono', max_length=10)),
                ('password', models.TextField()),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='MesaModel',
            fields=[
                ('mesaId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('mesaDescripcion', models.CharField(db_column='descripcion', max_length=10)),
                ('mesaCapacidad', models.IntegerField(db_column='capacidad')),
            ],
            options={
                'db_table': 'mesas',
            },
        ),
        migrations.CreateModel(
            name='PlatoModel',
            fields=[
                ('platoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('platoNombre', models.CharField(db_column='nombre', max_length=45, unique=True)),
                ('platoPrecio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=5)),
                ('platoFoto', models.ImageField(db_column='foto', null=True, upload_to='platos/')),
                ('platoCantidad', models.IntegerField(db_column='cantidad', default=0)),
            ],
            options={
                'db_table': 'platos',
                'ordering': ['platoNombre'],
            },
        ),
        migrations.CreateModel(
            name='PedidoModel',
            fields=[
                ('pedidoId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('pedidoFecha', models.DateTimeField(auto_now=True, db_column='fecha')),
                ('pedidoTotal', models.DecimalField(db_column='total', decimal_places=2, max_digits=5)),
                ('pedidoNombreCliente', models.CharField(db_column='nombre_cliente', max_length=45)),
                ('pedidoDocumentoCliente', models.CharField(db_column='documento_cliente', max_length=12)),
                ('mesa', models.ForeignKey(db_column='mesa_id', on_delete=django.db.models.deletion.PROTECT, related_name='mesaPedidos', to='cms.mesamodel')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='usuarioPedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedidos',
                'ordering': ['-pedidoFecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleModel',
            fields=[
                ('detalleId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('detalleCantidad', models.IntegerField(db_column='cantidad')),
                ('detalleSubTotal', models.DecimalField(db_column='sub_total', decimal_places=2, max_digits=5)),
                ('pedido', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.PROTECT, related_name='pedidoDetalles', to='cms.pedidomodel')),
                ('plato', models.ForeignKey(db_column='plato_id', on_delete=django.db.models.deletion.PROTECT, related_name='platoDetalles', to='cms.platomodel')),
            ],
            options={
                'db_table': 'detalles',
            },
        ),
    ]
