# Generated by Django 3.2.4 on 2021-06-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuarioApellido',
            field=models.CharField(db_column='apellido', max_length=20, verbose_name='Apellido del usuario'),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuarioCorreo',
            field=models.EmailField(db_column='correo', max_length=254, unique=True, verbose_name='Correo del usuario'),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuarioNombre',
            field=models.CharField(db_column='nombre', max_length=20, verbose_name='Nombre del usuario'),
        ),
        migrations.AlterField(
            model_name='usuariomodel',
            name='usuarioTipo',
            field=models.IntegerField(choices=[(1, 'ADMINISTRADOR'), (2, 'CAJERO'), (3, 'MOZO')], db_column='tipo', verbose_name='Tipo del usuario'),
        ),
    ]
