# Generated by Django 3.2.4 on 2021-06-25 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0002_agregue_related_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteModel',
            fields=[
                ('comprobanteId', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True)),
                ('comprobanteSerie', models.CharField(db_column='serie', max_length=4)),
                ('comprobanteNumero', models.IntegerField(db_column='numero')),
                ('comprobanteTipo', models.IntegerField(choices=[(1, 'BOLETA'), (2, 'FACTURA')], db_column='tipo')),
                ('comprobantePDF', models.TextField(db_column='PDF')),
                ('comprobanteCDR', models.TextField(db_column='CDR')),
                ('comprobanteXML', models.TextField(db_column='XML')),
                ('comprobanteDocCliente', models.CharField(db_column='doc_cliente', max_length=11)),
                ('pedido', models.OneToOneField(db_column='pedido_id', on_delete=django.db.models.deletion.CASCADE, related_name='pedidoComprobantes', to='cms.pedidomodel')),
            ],
        ),
    ]
