# Generated by Django 3.2.4 on 2021-06-25 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comprobantemodel',
            table='comprobantes',
        ),
    ]
