# Generated by Django 3.2.4 on 2021-06-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_cambie_nombre_tabla_comprobantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantemodel',
            name='comprobanteCDR',
            field=models.TextField(db_column='CDR', null=True),
        ),
    ]
